version: "3.9"

services:
  gateway:
    image: ksewen/gateway-for-test:0.0.1
    environment:
      JAVA_OPTS: -XX:InitialHeapSize=1g -XX:MaxHeapSize=1g -agentpath:/opt/jprofiler13/bin/linux-aarch64/libjprofilerti.so=port=8849,nowait
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 2048M
    ports:
      - 38071:8071
      - 38849:8849
    networks:
      - test_net

  service:
    image: ksewen/service-for-test:0.0.1
    environment:
      JAVA_OPTS: -XX:InitialHeapSize=1g -XX:MaxHeapSize=1g
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 2048M
    ports:
      - 38072:8072
    networks:
      - test_net

  auth-service:
    image: ksewen/auth-service-for-test:0.0.1
    environment:
      JAVA_OPTS: -XX:InitialHeapSize=1g -XX:MaxHeapSize=1g
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 2048M
    ports:
      - 38073:8073
    networks:
      - test_net


networks:
  test_net:
    driver: bridge
