server:
  port: 8071

spring:
  application:
    name: gateway-for-test
  cloud:
    gateway:
      routes:
        - id: test-router
          uri: http://service:8072/hello
          predicates:
            - Path=/service/**
          filters:
            - RewritePath=/service(?<segment>/?.*), $\{segment}
            - name: SimpleAuth
              args:
                url: http://auth-service:8073/auth